[tool.py2app.bundle.main]
  script = "TinyTinyEdit.py"
  resources = [ "MainMenu.nib", "TinyTinyDocument.nib" ]

[tool.py2app.bundle.main.plist]
  [[tool.py2app.bundle.main.plist.CFBundleDocumentTypes]]
  "CFBundleTypeExtensions" = ["txt", "text", "*"]
  "CFBundleTypeName" = "Text File"
  "CFBundleTypeRole" = "Editor"
  "NSDocumentClass" = "TinyTinyDocument"
